import React, { useState } from 'react';
import Navbar from './Navbar'; // Adjust the path to be relative to the current file's location
import Footer from './Footer'; // Adjust the path to be relative to the current file's location

const data = [
    {
      program: 'Génie informatique',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'algorithmique et complexité', description: 'Description du cours 1' },
            { id: 2, title: 'théorie de languages et compilation', description: 'Description du cours 2' },
            { id: 3, title: 'recherche operationnelle', description: 'Description du cours 3' },
            { id: 4, title: 'gestion de projets', description: 'Description du cours 4' },
            { id: 5, title: 'génie logiciel', description: 'Description du cours 5' },
            { id: 6, title: 'industrial internet of things ilot', description: 'Description du cours 6' },
            { id: 7, title: 'cloud computing', description: 'Description du cours 7' },
            { id: 8, title: 'modélisation des systèmes', description: 'Description du cours 8' },
            { id: 9, title: 'robotique', description: 'Description du cours 9' },
            { id: 10, title: 'système unix', description: 'Description du cours 10' },
            { id: 11, title: 'architecture des systèmes d\'exploitation', description: 'Description du cours 11' },
            { id: 12, title: 'architecture tcp/ip', description: 'Description du cours 12' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'Méthodes agiles en gestion de projets', description: 'Description du cours 1' },
            { id: 2, title: 'Projet fédérateur', description: 'Description du cours 2' },
            { id: 3, title: 'Architectures logicielles', description: 'Description du cours 3' },
            { id: 4, title: 'Sécurité de l information', description: 'Description du cours 1' },
            { id: 5, title: 'Data mining', description: 'Description du cours 2' },
            { id: 6, title: 'Développement web & mobile', description: 'Description du cours 3' },
            { id: 7, title: 'Systèmes embarqués', description: 'Description du cours 1' },
            { id: 8, title: 'Bases de données non relationnelles', description: 'Description du cours 1' },
            { id: 9, title: ' Management des ressources humaines', description: 'Description du cours 1' },
            { id: 10, title: 'Entrepreneuriat', description: 'Description du cours 2' },
            { id: 11, title: 'Évaluation financière et économique', description: 'Description du cours 3' },
            { id: 12, title: 'Simulation discrète', description: 'Description du cours 1' },
            { id: 13, title: 'Machine learning', description: 'Description du cours 1' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: "Système d'Information à Base Microservices" },
            { id: 2, title: 'Projet Fédérateur' },
            { id: 3, title: 'Cybersécurité' },
            { id: 4, title: 'Blockchain' },
            { id: 5, title: 'Enterprise Ressource Planning-ERP' },
            { id: 6, title: "Stratégie et Architecture d’Entreprise" },
            { id: 7, title: 'Robotic Process Management-BPM' },
            { id: 8, title: 'Robotic Process Automation-RPA' },
            { id: 9, title: 'Plateformes Big Data' },
            { id: 10, title: 'Visualisation de Données' },
            { id: 11, title: 'Business Intelligence - BI' },
            { id: 15, title: 'DataOps' },
    { id: 16, title: 'Projet Fédérateur' },
    { id: 17, title: 'Cybersécurité' },
    { id: 18, title: 'Blockchain' },
    { id: 19, title: 'Administration des Bases de Données' },
    { id: 20, title: 'Administration des Systèmes' },
    { id: 21, title: 'Administration des Réseaux' },
    { id: 22, title: 'Plateformes Big Data' },
    { id: 23, title: 'Visualisation de Données' },
    { id: 24, title: 'Business Intelligence - BI' }
        ],
        },
      ],
    },
    {
      program: 'Génie industriel',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'fabrication mécanique', description: 'Description du cours 1' },
            { id: 2, title: 'machine thermique', description: 'Description du cours 2' },
            { id: 3, title: 'machine électrique', description: 'Description du cours 3' },
            { id: 4, title: 'machine hydraulique', description: 'Description du cours 4' },
            { id: 5, title: 'recherche opérationnelle', description: 'Description du cours 5' },
            { id: 6, title: 'modélisation des systèmes complexes', description: 'Description du cours 6' },
            { id: 7, title: 'robotique', description: 'Description du cours 7' },
            { id: 8, title: 'vision industrielle', description: 'Description du cours 8' },
            { id: 9, title: 'supply chain', description: 'Description du cours 9' },
            { id: 10, title: 'distribution et transport', description: 'Description du cours 10' },
            { id: 11, title: 'réseaux informatique', description: 'Description du cours 11' },
            { id: 12, title: 'base de données', description: 'Description du cours 12' },
            { id: 13, title: 'vba / langage r / python / matlab', description: 'Description du cours 13' },
            { id: 14, title: 'gestion de projets', description: 'Description du cours 14' },
            { id: 15, title: 'pilotage de projets complexes', description: 'Description du cours 15' },
          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'maintenance industrielle', description: 'Description du cours 1' },
            { id: 2, title: 'système de production', description: 'Description du cours 2' },
            { id: 3, title: 'management stratégique des entreprises', description: 'Description du cours 3' },
            { id: 4, title: 'aide à la décision et métaheuristiques', description: 'Description du cours 4' },
            { id: 5, title: 'data mining', description: 'Description du cours 5' },
            { id: 6, title: 'gestion des risques et fiabilité', description: 'Description du cours 6' },
            { id: 7, title: 'management de la maintenance', description: 'Description du cours 7' },
            { id: 8, title: 'total productive maintenance et gmao', description: 'Description du cours 8' },
            { id: 9, title: 'inventory and production management', description: 'Description du cours 9' },
            { id: 10, title: 'lean manufacturing', description: 'Description du cours 10' },
            { id: 11, title: 'optimisation numérique', description: 'Description du cours 11' },
            { id: 12, title: 'management de la qualité', description: 'Description du cours 12' },
            { id: 13, title: 'entreprenariat', description: 'Description du cours 13' },
            { id: 14, title: 'évaluation financière et économique', description: 'Description du cours 14' },
            { id: 15, title: 'management des ressources humaines', description: 'Description du cours 15' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: "Outils d'Aide à la Décision" },
            { id: 2, title: 'Ingénierie Financière' },
            { id: 3, title: "Management des Systèmes d'Information" },
            { id: 4, title: 'Optimisation et Pilotage des Processus' },
            { id: 5, title: 'Extraction de Connaissances à partir de Données' },
            { id: 6, title: 'Ingénierie Durable et Innovation' },
            { id: 7, title: 'Arabe Technique' },
            { id: 8, title: 'Anglais' },
            { id: 9, title: "Techniques d'Expression" },
            { id: 10, title: "Outils d'Aide à la Décision" },
    { id: 11, title: 'Ingénierie Financière' },
    { id: 12, title: "Management des Systèmes d'Information" },
    { id: 13, title: 'Optimisation et Pilotage des Processus' },
    { id: 14, title: 'Extraction de Connaissances à partir de Données' },
    { id: 15, title: 'Méthodes de Prévision en Finance' },
    { id: 16, title: 'Méthodes de Prévision en Actuariat' },
        ],
        },
      ],
    },
    {
      program: 'Maintenance industrielle',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'fabrication mécanique', description: 'Description du cours 1' },
            { id: 2, title: 'technique d\'usinage', description: 'Description du cours 2' },
            { id: 3, title: 'machine asynchrone', description: 'Description du cours 3' },
            { id: 4, title: 'machine synchrone', description: 'Description du cours 4' },
            { id: 5, title: 'recherche operationnelle', description: 'Description du cours 5' },
            { id: 6, title: 'automatique des systèmes discrets', description: 'Description du cours 6' },
            { id: 7, title: 'informatique industrielle', description: 'Description du cours 7' },
            { id: 8, title: 'resistance des matériaux ii', description: 'Description du cours 8' },
            { id: 9, title: 'circuit hydraulique', description: 'Description du cours 9' },
            { id: 10, title: 'electronique industrielle', description: 'Description du cours 10' },
            { id: 11, title: 'electronique de puissance', description: 'Description du cours 11' },
            { id: 12, title: 'réseaux informatique', description: 'Description du cours 12' },
            { id: 13, title: 'base de données', description: 'Description du cours 13' },
            { id: 14, title: 'vba & vba.net', description: 'Description du cours 14' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'maintenance industrielle', description: 'Description du cours 1' },
            { id: 2, title: 'fiabilité des systèmes', description: 'Description du cours 2' },
            { id: 3, title: 'gestion de stocks', description: 'Description du cours 3' },
            { id: 4, title: 'ordonnancement', description: 'Description du cours 4' },
            { id: 5, title: 'système de production', description: 'Description du cours 5' },
            { id: 6, title: 'machine thermique', description: 'Description du cours 6' },
            { id: 7, title: 'pompe et compresseur', description: 'Description du cours 7' },
            { id: 8, title: 'transmission de puissance', description: 'Description du cours 8' },
            { id: 9, title: 'réseaux électrique en milieu industriel', description: 'Description du cours 9' },
            { id: 10, title: 'appareillage électrique', description: 'Description du cours 10' },
            { id: 11, title: 'gestion de la qualité', description: 'Description du cours 11' },
            { id: 12, title: 'entreprenariat', description: 'Description du cours 12' },
            { id: 13, title: 'évaluation financière et économique', description: 'Description du cours 13' },
            { id: 14, title: 'management des ressources humaines', description: 'Description du cours 14' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'conception des systèmes mécaniques', description: 'Description du cours 1' },
            { id: 2, title: 'analyse amdec', description: 'Description du cours 2' },
            { id: 3, title: 'lubrification', description: 'Description du cours 3' },
            { id: 4, title: 'maintenance des systèmes mécaniques', description: 'Description du cours 4' },
            { id: 5, title: 'sensibilisation à la sécurité', description: 'Description du cours 5' },
            { id: 6, title: 'contrôle de la qualité', description: 'Description du cours 6' },
            { id: 7, title: 'capteurs industriels', description: 'Description du cours 7' },
            { id: 8, title: 'maintenance prévisionnelle des machines tournantes', description: 'Description du cours 8' },
            { id: 9, title: 'total productive maintenance', description: 'Description du cours 9' },
            { id: 10, title: 'contrôle non destructif', description: 'Description du cours 10' },
            { id: 11, title: 'diagnostic et gmao', description: 'Description du cours 11' },
            { id: 12, title: 'utilisation rationnelle d\'énergie électrique', description: 'Description du cours 12' },
            { id: 13, title: 'coût de la maintenance', description: 'Description du cours 13' },
            { id: 14, title: 'gestion des risques industriels', description: 'Description du cours 14' },
            { id: 15, title: 'mécanique des vibrations', description: 'Description du cours 15' },
            { id: 16, title: 'traitement du signal', description: 'Description du cours 16' },          ],
        },
      ],
    },
    {
      program: 'Electromécanique',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'fabrication mécanique', description: 'Description du cours 1' },
            { id: 2, title: 'technique d\'usinage', description: 'Description du cours 2' },
            { id: 3, title: 'machine asynchrone', description: 'Description du cours 3' },
            { id: 4, title: 'machine synchrone', description: 'Description du cours 4' },
            { id: 5, title: 'recherche operationnelle', description: 'Description du cours 5' },
            { id: 6, title: 'automatique des systèmes discrets', description: 'Description du cours 6' },
            { id: 7, title: 'informatique industrielle', description: 'Description du cours 7' },
            { id: 8, title: 'resistance des matériaux ii', description: 'Description du cours 8' },
            { id: 9, title: 'circuit hydraulique', description: 'Description du cours 9' },
            { id: 10, title: 'electronique industrielle', description: 'Description du cours 10' },
            { id: 11, title: 'electronique de puissance', description: 'Description du cours 11' },
            { id: 12, title: 'réseaux informatique', description: 'Description du cours 12' },
            { id: 13, title: 'base de données', description: 'Description du cours 13' },
            { id: 14, title: 'vba & vba.net', description: 'Description du cours 14' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'maintenance industrielle', description: 'Description du cours 1' },
            { id: 2, title: 'comptoir electrique & de mesure', description: 'Description du cours 2' },
            { id: 3, title: 'systèmes embarqués', description: 'Description du cours 3' },
            { id: 4, title: 'machine asynchrone', description: 'Description du cours 4' },
            { id: 5, title: 'centrale électrique', description: 'Description du cours 5' },
            { id: 6, title: 'système de production', description: 'Description du cours 6' },
            { id: 7, title: 'machine thermique', description: 'Description du cours 7' },
            { id: 8, title: 'pompe et compresseur', description: 'Description du cours 8' },
            { id: 9, title: 'transmission de puissance', description: 'Description du cours 9' },
            { id: 10, title: 'réseaux électrique en milieu industriel', description: 'Description du cours 10' },
            { id: 11, title: 'appareillage électrique', description: 'Description du cours 11' },
            { id: 12, title: 'gestion de la qualité', description: 'Description du cours 12' },
            { id: 13, title: 'entreprenariat', description: 'Description du cours 13' },
            { id: 14, title: 'evaluation financière et économique', description: 'Description du cours 14' },
            { id: 15, title: 'management des ressources humaines', description: 'Description du cours 15' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'transmission de puissance ii', description: 'Description du cours 1' },
            { id: 2, title: 'association convertisseurs machines', description: 'Description du cours 2' },
            { id: 3, title: 'lubrification et maintenance des mécanismes', description: 'Description du cours 3' },
            { id: 4, title: 'notion de la compatibilité', description: 'Description du cours 4' },
            { id: 5, title: 'électromagnétique', description: 'Description du cours 5' },
            { id: 6, title: 'dao/cao', description: 'Description du cours 6' },
            { id: 7, title: 'qualité de l\'énergie électrique', description: 'Description du cours 7' },
            { id: 8, title: 'les machines à commandes numériques', description: 'Description du cours 8' },
            { id: 9, title: 'utilisation rationnelle de l\'énergie électrique', description: 'Description du cours 9' },
            { id: 10, title: 'travaux pratiques de fabrication', description: 'Description du cours 10' },
            { id: 11, title: 'modélisation dynamique des machines tournantes', description: 'Description du cours 11' },
            { id: 12, title: 'mécanique des vibrations', description: 'Description du cours 12' },
            { id: 13, title: 'étude linéaire', description: 'Description du cours 13' },
            { id: 14, title: 'mécanique des structures', description: 'Description du cours 14' },
            { id: 15, title: 'traitement du signal et analyse vibratoire', description: 'Description du cours 15' },          ],
        },
      ],
    },
    {
      program: 'Environnement et sécurité industrielle',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'Eau et Pollution de l\'Eau', description: 'Description du cours' },
            { id: 2, title: 'Assainissement', description: 'Description du cours' },
            { id: 3, title: 'Pollution du Sol', description: 'Description du cours' },
            { id: 4, title: 'Métrologie Environnementale', description: 'Description du cours' },
            { id: 5, title: 'Thermodynamique des Équilibres', description: 'Description du cours' },
            { id: 6, title: 'Transfert de Matière', description: 'Description du cours' },
            { id: 7, title: 'Cinétique Chimique', description: 'Description du cours' },
            { id: 8, title: 'Recherche Opérationnelle', description: 'Description du cours' },
            { id: 9, title: 'Réseaux Informatique', description: 'Description du cours' },
            { id: 10, title: 'Base de Données', description: 'Description du cours' },
            { id: 11, title: 'VBA & VBA.NET', description: 'Description du cours' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'SIG', description: 'Description du cours' },
            { id: 2, title: 'Topographie', description: 'Description du cours' },
            { id: 3, title: 'Biologie', description: 'Description du cours' },
            { id: 4, title: 'Écologie', description: 'Description du cours' },
            { id: 5, title: 'Éco-Toxicologie', description: 'Description du cours' },
            { id: 6, title: 'Procédés Industriels', description: 'Description du cours' },
            { id: 7, title: 'Technologies Propres', description: 'Description du cours' },
            { id: 8, title: 'Santé & Sécurité au Travail', description: 'Description du cours' },
            { id: 9, title: 'Gestion des Produits Chimiques', description: 'Description du cours' },
            { id: 10, title: 'Développement Durable', description: 'Description du cours' },
            { id: 11, title: 'Système de Production', description: 'Description du cours' },
            { id: 12, title: 'Gestion de la Qualité', description: 'Description du cours' },
            { id: 13, title: 'Maintenance Industrielle', description: 'Description du cours' },
            { id: 14, title: 'Entrepreneuriat', description: 'Description du cours' },
            { id: 15, title: 'Évaluation Financière et Économique', description: 'Description du cours' },
            { id: 16, title: 'Management des Ressources Humaines', description: 'Description du cours' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'Étude d\'Impact sur l\'Environnement', description: 'Description du cours' },
            { id: 2, title: 'Analyse Dangers et Évaluation des Risques Professionnels', description: 'Description du cours' },
            { id: 3, title: 'Audit Environnementale', description: 'Description du cours' },
            { id: 4, title: 'Concept de la Qualité', description: 'Description du cours' },
            { id: 5, title: 'SME et SMI', description: 'Description du cours' },
            { id: 6, title: 'HACCP', description: 'Description du cours' },
            { id: 7, title: 'Procédés Agro-Industriels', description: 'Description du cours' },
            { id: 8, title: 'Analyse du Cycle de Vie', description: 'Description du cours' },
            { id: 9, title: 'Techniques Séparatives', description: 'Description du cours' },
            { id: 10, title: 'Réglementation Environnementale', description: 'Description du cours' },
            { id: 11, title: 'Traitement des Déchets', description: 'Description du cours' },
            { id: 12, title: 'Pollution de l\'Air', description: 'Description du cours' },
            { id: 13, title: 'Traitement des Eaux', description: 'Description du cours' },
            { id: 14, title: 'Gestion des Risques', description: 'Description du cours' },          ],
        },
      ],
    },
    {
      program: 'Génie productique',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'algorithmique et complexité', description: 'Description du cours 1' },
            { id: 2, title: 'théorie de languages et compilation', description: 'Description du cours 2' },
            { id: 3, title: 'recherche operationnelle', description: 'Description du cours 3' },
            { id: 4, title: 'gestion de projets', description: 'Description du cours 4' },
            { id: 5, title: 'génie logiciel', description: 'Description du cours 5' },
            { id: 6, title: 'cloud computing', description: 'Description du cours 6' },
            { id: 7, title: 'modélisation des systèmes', description: 'Description du cours 7' },
            { id: 8, title: 'robotique', description: 'Description du cours 8' },
            { id: 9, title: 'architecture des systèmes d\'exploitation', description: 'Description du cours 9' },
            { id: 10, title: 'architecture tcp/ip', description: 'Description du cours 10' },
            { id: 11, title: 'gestion de production', description: 'Description du cours 11' },
            { id: 12, title: 'gestion de la qualité', description: 'Description du cours 12' },
            { id: 13, title: 'industrial internet of things', description: 'Description du cours 13' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'maintenance industrielle', description: 'Description du cours 1' },
            { id: 2, title: 'système de production', description: 'Description du cours 2' },
            { id: 3, title: 'réseaux de file d\'attente et simulation', description: 'Description du cours 3' },
            { id: 4, title: 'supply chain management', description: 'Description du cours 4' },
            { id: 5, title: 'informatique industrielle', description: 'Description du cours 5' },
            { id: 6, title: 'automatique', description: 'Description du cours 6' },
            { id: 7, title: 'data mining', description: 'Description du cours 7' },
            { id: 8, title: 'bases de données non relationnelles', description: 'Description du cours 8' },
            { id: 9, title: 'système embarqués', description: 'Description du cours 9' },
            { id: 10, title: 'entrepreneuriat', description: 'Description du cours 10' },
            { id: 11, title: 'evaluation financière et économique', description: 'Description du cours 11' },
            { id: 12, title: 'management des ressources humaines', description: 'Description du cours 12' },
            { id: 13, title: 'simulation discrète', description: 'Description du cours 13' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'mapitrise statistique des procédés', description: 'Description du cours 1' },
            { id: 2, title: 'systèmes de management de la qualité', description: 'Description du cours 2' },
            { id: 3, title: 'lear manufacturing', description: 'Description du cours 3' },
            { id: 4, title: 'total productive maintenance', description: 'Description du cours 4' },
            { id: 5, title: 'big data', description: 'Description du cours 5' },
            { id: 6, title: 'visualisation des données', description: 'Description du cours 6' },
            { id: 7, title: 'business intelligence', description: 'Description du cours 7' },
            { id: 8, title: 'analyse multicritère', description: 'Description du cours 8' },
            { id: 9, title: 'réseaux de petri', description: 'Description du cours 9' },
            { id: 10, title: 'gestion des risques industriel', description: 'Description du cours 10' },
            { id: 11, title: 'fiabilité des systèmes', description: 'Description du cours 11' },
            { id: 12, title: 'enterprise resource planning', description: 'Description du cours 12' },
            { id: 13, title: 'projet fédérateur', description: 'Description du cours 13' },          ],
        },
      ],
    },
    {
      program: 'Efficacité énergétique et intégration des énergies renouvelables',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'fabrication mécanique', description: 'Description du cours 1' },
            { id: 2, title: 'technique d\'usinage', description: 'Description du cours 2' },
            { id: 3, title: 'machine asynchrone', description: 'Description du cours 3' },
            { id: 4, title: 'machine synchrone', description: 'Description du cours 4' },
            { id: 5, title: 'recherche operationnelle', description: 'Description du cours 5' },
            { id: 6, title: 'automatique des systèmes discrets', description: 'Description du cours 6' },
            { id: 7, title: 'informatique industrielle', description: 'Description du cours 7' },
            { id: 8, title: 'resistance des matériaux ii', description: 'Description du cours 8' },
            { id: 9, title: 'circuit hydraulique', description: 'Description du cours 9' },
            { id: 10, title: 'electronique industrielle', description: 'Description du cours 10' },
            { id: 11, title: 'electronique de puissance', description: 'Description du cours 11' },
            { id: 12, title: 'réseaux informatique', description: 'Description du cours 12' },
            { id: 13, title: 'base de données', description: 'Description du cours 13' },
            { id: 14, title: 'vba & vba.net', description: 'Description du cours 14' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'stockage', description: 'Description du cours 1' },
            { id: 2, title: 'système embarqué', description: 'Description du cours 2' },
            { id: 3, title: 'énergie éolienne', description: 'Description du cours 3' },
            { id: 4, title: 'énergie solaire photovoltaïque', description: 'Description du cours 4' },
            { id: 5, title: 'centrale électrique', description: 'Description du cours 5' },
            { id: 6, title: 'système de production', description: 'Description du cours 6' },
            { id: 7, title: 'machine thermique', description: 'Description du cours 7' },
            { id: 8, title: 'pompe et compresseur', description: 'Description du cours 8' },
            { id: 9, title: 'transmission de puissance', description: 'Description du cours 9' },
            { id: 10, title: 'réseaux électrique en milieu industriel', description: 'Description du cours 10' },
            { id: 11, title: 'appareillage électrique', description: 'Description du cours 11' },
            { id: 12, title: 'gestion de la qualité', description: 'Description du cours 12' },
            { id: 13, title: 'maintenance industrielle', description: 'Description du cours 13' },
            { id: 14, title: 'entreprenariat', description: 'Description du cours 14' },
            { id: 15, title: 'evaluation financière et économique', description: 'Description du cours 15' },
            { id: 16, title: 'management des ressources humaines', description: 'Description du cours 16' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'système de management de l\'énergie', description: 'Description du cours 1' },
            { id: 2, title: 'audit énergétique et bilan carbone', description: 'Description du cours 2' },
            { id: 3, title: 'fiabilité et outils de la maintenance', description: 'Description du cours 3' },
            { id: 4, title: 'intégration des énergies renouvelables', description: 'Description du cours 4' },
            { id: 5, title: 'biomasse et geothermie', description: 'Description du cours 5' },
            { id: 6, title: 'micros turbines hydrauliques', description: 'Description du cours 6' },
            { id: 7, title: 'efficacité énergétique', description: 'Description du cours 7' },
            { id: 8, title: 'production et stockage énergétique durable', description: 'Description du cours 8' },
            { id: 9, title: 'sécurité industrielle et digitalisation', description: 'Description du cours 9' },          ],
        },
      ],
    },
    {
      program: 'Génie énergétique',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'séparation mecanique', description: 'Description du cours 1' },
            { id: 2, title: 'énergie éolienne', description: 'Description du cours 2' },
            { id: 3, title: 'énergie nucléaire et sécurité nucléaire', description: 'Description du cours 3' },
            { id: 4, title: 'énergies renouvelables', description: 'Description du cours 4' },
            { id: 5, title: 'distillation', description: 'Description du cours 5' },
            { id: 6, title: 'thermodynamique des équilibres', description: 'Description du cours 6' },
            { id: 7, title: 'production et distribution de vapeur', description: 'Description du cours 7' },
            { id: 8, title: 'technique de combustion et chaudière', description: 'Description du cours 8' },
            { id: 9, title: 'hydraulique', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique des équilibres', description: 'Description du cours 10' },
            { id: 11, title: 'production et distribution de vapeur', description: 'Description du cours 11' },
            { id: 12, title: 'recherche operationnelle', description: 'Description du cours 12' },
            { id: 13, title: 'réseaux informatique', description: 'Description du cours 13' },
            { id: 14, title: 'base de données', description: 'Description du cours 14' },
            { id: 15, title: 'vba & vba.net', description: 'Description du cours 15' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'modelisation et simulation', description: 'Description du cours 1' },
            { id: 2, title: 'optimisation et conduite des procedes', description: 'Description du cours 2' },
            { id: 3, title: 'calcul d\'echangeurs de chaleur', description: 'Description du cours 3' },
            { id: 4, title: 'moteur thermique', description: 'Description du cours 4' },
            { id: 5, title: 'pompes et compresseurs', description: 'Description du cours 5' },
            { id: 6, title: 'etudes de cas', description: 'Description du cours 6' },
            { id: 7, title: 'sechage et humidification', description: 'Description du cours 7' },
            { id: 8, title: 'reseaux electriques', description: 'Description du cours 8' },
            { id: 9, title: 'bilan & analogie des phenomenes de transfert', description: 'Description du cours 9' },
            { id: 10, title: 'système de production', description: 'Description du cours 10' },
            { id: 11, title: 'gestion de la qualite', description: 'Description du cours 11' },
            { id: 12, title: 'maintenance industrielle', description: 'Description du cours 12' },
            { id: 13, title: 'entrepreneuriat', description: 'Description du cours 13' },
            { id: 14, title: 'evaluation financière et économique', description: 'Description du cours 14' },
            { id: 15, title: 'management des ressources humaines', description: 'Description du cours 15' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'utilisation rationnelle d\'energie electrique', description: 'Description du cours 1' },
            { id: 2, title: 'production du froid', description: 'Description du cours 2' },
            { id: 3, title: 'regulation de l\'energie electrique', description: 'Description du cours 3' },
            { id: 4, title: 'moteurs à combustion à flux continu', description: 'Description du cours 4' },
            { id: 5, title: 'qualite de l\'energie electrique', description: 'Description du cours 5' },
            { id: 6, title: 'energetique du batiment', description: 'Description du cours 6' },
            { id: 7, title: 'techniques d\'audit energetique', description: 'Description du cours 7' },
            { id: 8, title: 'audits electrique', description: 'Description du cours 8' },
            { id: 9, title: 'evaluation economique des procedes', description: 'Description du cours 9' },
            { id: 10, title: 'etude d\'impact environnemental', description: 'Description du cours 10' },
            { id: 11, title: 'gestion et projet energetique', description: 'Description du cours 11' },          ],
        },
      ],
    },
    {
      program: 'Matériaux et contrôle qualité',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'calcul des structures et modelisation', description: 'Description du cours 1' },
            { id: 2, title: 'fabrication mécanique', description: 'Description du cours 2' },
            { id: 3, title: 'elasticité - plasticité', description: 'Description du cours 3' },
            { id: 4, title: 'transmission de puissance', description: 'Description du cours 4' },
            { id: 5, title: 'métallurgie physique', description: 'Description du cours 5' },
            { id: 6, title: 'techniques de caractérisation', description: 'Description du cours 6' },
            { id: 7, title: 'thermodynamique des matériaux', description: 'Description du cours 7' },
            { id: 8, title: 'recherche operationnelle', description: 'Description du cours 8' },
            { id: 9, title: 'resistance des matériaux ii', description: 'Description du cours 9' },
            { id: 10, title: 'circuit hydraulique', description: 'Description du cours 10' },
            { id: 11, title: 'réseaux informatique', description: 'Description du cours 11' },
            { id: 12, title: 'base de données', description: 'Description du cours 12' },
            { id: 13, title: 'vba & vba.net', description: 'Description du cours 13' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'electrochimie appliquée', description: 'Description du cours 1' },
            { id: 2, title: 'corrosion et protection', description: 'Description du cours 2' },
            { id: 3, title: 'traitement thermique', description: 'Description du cours 3' },
            { id: 4, title: 'fonderie', description: 'Description du cours 4' },
            { id: 5, title: 'les matériaux de construction', description: 'Description du cours 5' },
            { id: 6, title: 'charpente métallique', description: 'Description du cours 6' },
            { id: 7, title: 'management des risques', description: 'Description du cours 7' },
            { id: 8, title: 'norme de l’environnement', description: 'Description du cours 8' },
            { id: 9, title: 'système de production', description: 'Description du cours 9' },
            { id: 10, title: 'gestion de la qualité', description: 'Description du cours 10' },
            { id: 11, title: 'maintenance industrielle', description: 'Description du cours 11' },
            { id: 12, title: 'entreprenariat', description: 'Description du cours 12' },
            { id: 13, title: 'évaluation financière et économique', description: 'Description du cours 13' },
            { id: 14, title: 'management des ressources humaines', description: 'Description du cours 14' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'choix de matériaux', description: 'Description du cours 1' },
            { id: 2, title: 'contrôles non destructifs', description: 'Description du cours 2' },
            { id: 3, title: 'assemblages soudés', description: 'Description du cours 3' },
            { id: 4, title: 'mécanique de la rupture et fatigue', description: 'Description du cours 4' },
            { id: 5, title: 'procédés de fabrication', description: 'Description du cours 5' },
            { id: 6, title: 'système de management de la qualité', description: 'Description du cours 6' },
            { id: 7, title: 'usure des matériaux', description: 'Description du cours 7' },
            { id: 8, title: 'contrôle de la qualité', description: 'Description du cours 8' },
            { id: 9, title: 'tpm', description: 'Description du cours 9' },
            { id: 10, title: 'amdec', description: 'Description du cours 10' },
            { id: 11, title: 'gmao & diagnostics', description: 'Description du cours 11' },
            { id: 12, title: 'composites & nouveaux matériaux', description: 'Description du cours 12' },
            { id: 13, title: 'plastiques', description: 'Description du cours 13' },
            { id: 14, title: 'céramiques', description: 'Description du cours 14' },          ],
        },
      ],
    },
    {
      program: 'Procédés industriels ',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'séparation mecanique', description: 'Description du cours 1' },
            { id: 2, title: 'absorption', description: 'Description du cours 2' },
            { id: 3, title: 'distillation', description: 'Description du cours 3' },
            { id: 4, title: 'thermodynamique des équilibres', description: 'Description du cours 4' },
            { id: 5, title: 'production et distribution de vapeur', description: 'Description du cours 5' },
            { id: 6, title: 'cinétique chimique', description: 'Description du cours 6' },
            { id: 7, title: 'hydraulique', description: 'Description du cours 7' },
            { id: 8, title: 'transfert de matiere', description: 'Description du cours 8' },
            { id: 9, title: 'recherche operationnelle', description: 'Description du cours 9' },
            { id: 10, title: 'réseaux informatique', description: 'Description du cours 10' },
            { id: 11, title: 'base de données', description: 'Description du cours 11' },
            { id: 12, title: 'vba & vba.net', description: 'Description du cours 12' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'modelisation et simulation', description: 'Description du cours 1' },
            { id: 2, title: 'optimisation et conduite des procedes', description: 'Description du cours 2' },
            { id: 3, title: 'calcul d\'échangeurs de chaleur', description: 'Description du cours 3' },
            { id: 4, title: 'procedes industriels', description: 'Description du cours 4' },
            { id: 5, title: 'pompes et compresseurs', description: 'Description du cours 5' },
            { id: 6, title: 'etudes de cas', description: 'Description du cours 6' },
            { id: 7, title: 'sechage et humidification', description: 'Description du cours 7' },
            { id: 8, title: 'extraction liquide', description: 'Description du cours 8' },
            { id: 9, title: 'bilan & analogie des phenomenes de transfert', description: 'Description du cours 9' },
            { id: 10, title: 'système de production', description: 'Description du cours 10' },
            { id: 11, title: 'gestion de la qualité', description: 'Description du cours 11' },
            { id: 12, title: 'maintenance industrielle', description: 'Description du cours 12' },
            { id: 13, title: 'entreprenariat', description: 'Description du cours 13' },
            { id: 14, title: 'evaluation financière et économique', description: 'Description du cours 14' },
            { id: 15, title: 'management des ressources humaines', description: 'Description du cours 15' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'projet d\'usine', description: 'Description du cours 1' },
            { id: 2, title: 'biotechnologies', description: 'Description du cours 2' },
            { id: 3, title: 'chimie des polymères', description: 'Description du cours 3' },
            { id: 4, title: 'procédés de filtration', description: 'Description du cours 4' },
            { id: 5, title: 'analyse et calcul des réacteurs', description: 'Description du cours 5' },
            { id: 6, title: 'évaluation économique des procédés', description: 'Description du cours 6' },
            { id: 7, title: 'étude d\'impact environnemental', description: 'Description du cours 7' },
            { id: 8, title: 'opérations de traitement des eaux', description: 'Description du cours 8' },
            { id: 9, title: 'sécurité des procédés et analyse des risques', description: 'Description du cours 9' },          ],
        },
      ],
    },
    {
      program: 'Aménagement et exploitation des sols et des sous-sols',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'Géologie de l\'Ingénieur', description: 'Description du cours 1' },
            { id: 2, title: 'Géologie des Gites Miniers', description: 'Description du cours 2' },
            { id: 3, title: 'Géostatistique', description: 'Description du cours 3' },
            { id: 4, title: 'Les Méthodes d\'Exploitation', description: 'Description du cours 4' },
            { id: 5, title: 'Principe et Critère de Choix', description: 'Description du cours 5' },
            { id: 6, title: 'Travaux Miniers', description: 'Description du cours 6' },
            { id: 7, title: 'Géotechnique', description: 'Description du cours 7' },
            { id: 8, title: 'RDM II', description: 'Description du cours 8' },
            { id: 9, title: 'Géophysique Appliquée', description: 'Description du cours 9' },
            { id: 10, title: 'Traitement d\'Image', description: 'Description du cours 10' },
            { id: 11, title: 'Transfert de Matière', description: 'Description du cours 11' },
            { id: 12, title: 'Recherche Operationnelle', description: 'Description du cours 12' },
            { id: 13, title: 'Réseaux Informatique', description: 'Description du cours 13' },
            { id: 14, title: 'Base de Données', description: 'Description du cours 14' },
            { id: 15, title: 'VBA & VBA.NET', description: 'Description du cours 15' },
          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'La Chaine de Production', description: 'Description du cours 1' },
            { id: 2, title: 'L\'Aérage des Ouvrages Souterrains', description: 'Description du cours 2' },
            { id: 3, title: 'L\'Exhaure', description: 'Description du cours 3' },
            { id: 4, title: 'La Mécanique des Roches', description: 'Description du cours 4' },
            { id: 5, title: 'La Modélisation en Géomécanique', description: 'Description du cours 5' },
            { id: 6, title: 'Hydraulique', description: 'Description du cours 6' },
            { id: 7, title: 'Minéralogie Appliquée à l\'Étude des Minerais', description: 'Description du cours 7' },
            { id: 8, title: 'Préparation Mécanique de Minerai', description: 'Description du cours 8' },
            { id: 9, title: 'Outils de Numérisation', description: 'Description du cours 9' },
            { id: 10, title: 'Ordonnancement', description: 'Description du cours 10' },
            { id: 11, title: 'Ateliers d\'Innovation et de Digitalisation', description: 'Description du cours 11' },
            { id: 12, title: 'Système de Production', description: 'Description du cours 12' },
            { id: 13, title: 'Gestion de la Qualité', description: 'Description du cours 13' },
            { id: 14, title: 'Maintenance Industrielle', description: 'Description du cours 14' },
            { id: 15, title: 'Entreprenariat', description: 'Description du cours 15' },
            { id: 16, title: 'Évaluation Financière et Économique', description: 'Description du cours 16' },
            { id: 17, title: 'Management des Ressources Humaines', description: 'Description du cours 17' },
          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'Géomécanique II', description: 'Description du cours 1' },
            { id: 2, title: 'Approches Empiriques de Stabilité', description: 'Description du cours 2' },
            { id: 3, title: 'Procédés Minéralurgiques', description: 'Description du cours 3' },
            { id: 4, title: 'Métallurgie Extractive', description: 'Description du cours 4' },
            { id: 5, title: 'Modélisation et Analyse Spaciale', description: 'Description du cours 5' },
            { id: 6, title: 'Géotechnique II', description: 'Description du cours 6' },
            { id: 7, title: 'Gestion des Ressources Naturelles', description: 'Description du cours 7' },
            { id: 8, title: 'Environnement et Contrôle Qualité', description: 'Description du cours 8' },
          ],
        },
      ],
    },
    {
      program: 'Génie civil et minier',
      levels: [
        {
          level: 'Semestre 1',
          courses: [
            { id: 1, title: 'Automatique', description: 'Description du cours 1' },
            { id: 2, title: 'Instrumentation et métrologie', description: 'Description du cours 2' },
            { id: 3, title: 'Électrotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'Dessin industriel technologie', description: 'Description du cours 4' },
            { id: 5, title: 'Analyse numérique', description: 'Description du cours 5' },
            { id: 6, title: 'Mathématiques', description: 'Description du cours 6' },
            { id: 7, title: 'Algorithmique', description: 'Description du cours 7' },
            { id: 8, title: 'Langage C', description: 'Description du cours 8' },
            { id: 9, title: 'Mécanique des fluides', description: 'Description du cours 9' },
            { id: 10, title: 'Mécanique des milieux continus', description: 'Description du cours 10' },
            { id: 11, title: 'Économie de l\'entreprise', description: 'Description du cours 11' },
            { id: 12, title: 'Management', description: 'Description du cours 12' },
            { id: 13, title: 'Anglais', description: 'Description du cours 13' },
            { id: 14, title: 'Techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'Minéralogie (Génie Civil Et Minier)', description: 'Description du cours 15' },
            { id: 16, title: 'Pétrologie magmatique ', description: '(Génie Civil Et Minier)' },
            { id: 17, title: 'Pétrologie métamorphique ', description: '(Génie Civil Et Minier)' },
            { id: 18, title: 'Pétrologie sédimentaire ', description: '(Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 2',
          courses: [
            { id: 1, title: 'théorie d\'échantillonnage', description: 'Description du cours 1' },
            { id: 2, title: 'statistiques inférentielle', description: 'Description du cours 2' },
            { id: 3, title: 'résistance des matériaux', description: 'Description du cours 3' },
            { id: 4, title: 'matériaux', description: 'Description du cours 4' },
            { id: 5, title: 'uml', description: 'Description du cours 5' },
            { id: 6, title: 'langage c++ / c avancé', description: 'Description du cours 6' },
            { id: 7, title: 'automatismes', description: 'Description du cours 7' },
            { id: 8, title: 'electronique', description: 'Description du cours 8' },
            { id: 9, title: 'transferts thermiques', description: 'Description du cours 9' },
            { id: 10, title: 'thermodynamique appliqué', description: 'Description du cours 10' },
            { id: 11, title: 'compatibilité', description: 'Description du cours 11' },
            { id: 12, title: 'finances', description: 'Description du cours 12' },
            { id: 13, title: 'anglais', description: 'Description du cours 13' },
            { id: 14, title: 'techniques d\'expression', description: 'Description du cours 14' },
            { id: 15, title: 'bases de données relationnelles ', description: '(Génie Informatique)' },
            { id: 16, title: 'réseaux informatique ', description: '(Génie Informatique)' },
            { id: 17, title: 'structures de données ', description: '(Génie Informatique)' },
            { id: 18, title: 'géologie structural ', description: '(Génie Civil Et Minier)' },
            { id: 19, title: 'cartographie ', description: ' (Génie Civil Et Minier)' },          ],
        },
        {
          level: 'Semestre 3',
          courses: [
            { id: 1, title: 'mécanique des sols', description: 'Description du cours 1' },
            { id: 2, title: 'mécanique des roches', description: 'Description du cours 2' },
            { id: 3, title: 'géotechnique', description: 'Description du cours 3' },
            { id: 4, title: 'hydrologie appliquée', description: 'Description du cours 4' },
            { id: 5, title: 'hydrologie statistique', description: 'Description du cours 5' },
            { id: 6, title: 'matériaux de construction', description: 'Description du cours 6' },
            { id: 7, title: 'substances utiles', description: 'Description du cours 7' },
            { id: 8, title: 'résistance des matériaux ii', description: 'Description du cours 8' },
            { id: 9, title: 'hydraulique appliqué', description: 'Description du cours 9' },
            { id: 10, title: 'recherche operationnelle', description: 'Description du cours 10' },
            { id: 11, title: 'réseaux informatique', description: 'Description du cours 11' },
            { id: 12, title: 'base de données', description: 'Description du cours 12' },
            { id: 13, title: 'vba & vba.net', description: 'Description du cours 13' },          ],
        },
        {
          level: 'Semestre 4',
          courses: [
            { id: 1, title: 'topographie', description: 'Description du cours 1' },
            { id: 2, title: 'sig', description: 'Description du cours 2' },
            { id: 3, title: 'télédétection', description: 'Description du cours 3' },
            { id: 4, title: 'procédés gé.de construction', description: 'Description du cours 4' },
            { id: 5, title: 'urbanisme et architecture', description: 'Description du cours 5' },
            { id: 6, title: 'hydrodynamique des milieux poreux', description: 'Description du cours 6' },
            { id: 7, title: 'hydrogéologie de l’ingénieur', description: 'Description du cours 7' },
            { id: 8, title: 'méthodes d\'exploration passive /actives', description: 'Description du cours 8' },
            { id: 9, title: 'diagraphies', description: 'Description du cours 9' },
            { id: 10, title: 'sondages et forages', description: 'Description du cours 10' },
            { id: 11, title: 'système de production', description: 'Description du cours 11' },
            { id: 12, title: 'gestion de la qualité', description: 'Description du cours 12' },
            { id: 13, title: 'maintenance industrielle', description: 'Description du cours 13' },
            { id: 14, title: 'entreprenariat', description: 'Description du cours 14' },
            { id: 15, title: 'évaluation financière et économique', description: 'Description du cours 15' },
            { id: 16, title: 'management des ressources humaines', description: 'Description du cours 16' },          ],
        },
        {
          level: 'Semestre 5',
          courses: [
            { id: 1, title: 'Hydraulique des Puits et Tranchés', description: 'Description du cours' },
            { id: 2, title: 'Modélisation des Écouls Souterrains', description: 'Description du cours' },
            { id: 3, title: 'Tracés Routiers', description: 'Description du cours' },
            { id: 4, title: 'Dimensionnement et Entretien Chaussées', description: 'Description du cours' },
            { id: 5, title: 'Hydraulique des Routes', description: 'Description du cours' },
            { id: 6, title: 'Béton Précontraint', description: 'Description du cours' },
            { id: 7, title: 'Conception et Dimensionnement des Ponts', description: 'Description du cours' },
            { id: 8, title: 'Conception et Calcul des Fondations', description: 'Description du cours' },
            { id: 9, title: 'Ouvrages Géotechniques', description: 'Description du cours' },
            { id: 10, title: 'Modélisation en Géomécanique', description: 'Description du cours' },
            { id: 11, title: 'Barrage et Ouvrages Annexes', description: 'Description du cours' },
            { id: 12, title: 'Réglementation en BTP', description: 'Description du cours' },
            { id: 13, title: 'Gestion des Marchés Publics', description: 'Description du cours' },
            { id: 14, title: 'Calcul des Structures des Bâtiments', description: 'Description du cours' },
            { id: 15, title: 'Efficacité Énergétique dans le Bâtiment', description: 'Description du cours' },
            { id: 16, title: 'Béton Précontraint', description: 'Description du cours' },
            { id: 17, title: 'Conception et Dimensionnement des Ponts', description: 'Description du cours' },
            { id: 18, title: 'Ouvrages Géotechniques', description: 'Description du cours' },
            { id: 19, title: 'Modélisation en Géomécanique', description: 'Description du cours' },
            { id: 20, title: 'Conception et Calcul des Fondations', description: 'Description du cours' },
            { id: 21, title: 'Construction Métallique', description: 'Description du cours' },
            { id: 22, title: 'Hydraulique des Puits et Tranchés', description: 'Description du cours' },
            { id: 23, title: 'Modélisation des Écouls Souterrains', description: 'Description du cours' },
            { id: 24, title: 'Réglementation en BTP', description: 'Description du cours' },
            { id: 25, title: 'Gestion des Marchés Publics', description: 'Description du cours' },
            { id: 26, title: 'Hydraulique des Puits et Tranchés', description: 'Description du cours' },
            { id: 27, title: 'Modélisation des Écouls Souterrains', description: 'Description du cours' },
            { id: 28, title: 'Conception et Calcul des Fondations', description: 'Description du cours' },
            { id: 29, title: 'Géothermie', description: 'Description du cours' },
            { id: 30, title: 'Métallurgie', description: 'Description du cours' },
            { id: 31, title: 'Phosphates', description: 'Description du cours' },
            { id: 32, title: 'Géostatistique', description: 'Description du cours' },
            { id: 33, title: 'Géochimie Fondamentale', description: 'Description du cours' },
            { id: 34, title: 'Géochimie Appliquée à l\'Exploration Minière', description: 'Description du cours' },
            { id: 35, title: 'Méthodes d\'Exploitation', description: 'Description du cours' },
            { id: 36, title: 'Mines et Gîtes du Maroc', description: 'Description du cours' },
            { id: 37, title: 'Ouvrages Géotechniques', description: 'Description du cours' },
            { id: 38, title: 'Modélisation en Géomécanique', description: 'Description du cours' },
            { id: 39, title: 'Code Minier Marocain', description: 'Description du cours' },
            { id: 40, title: 'Gestion des Marchés Publics', description: 'Description du cours' },
            { id: 41, title: 'Arabe Technique', description: 'Description du cours' },
            { id: 42, title: 'Anglais', description: 'Description du cours' },
            { id: 43, title: 'Techniques d\'Expression', description: 'Description du cours' },
        ],
        },
      ],
    },
  ];
  

const Rechercher = () => {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);

  const handleSearch = (e) => {
    setQuery(e.target.value);
    if (e.target.value === '') {
      setResults([]);
    } else {
      const filteredResults = [];
      data.forEach(program => {
        program.levels.forEach(level => {
          level.courses.forEach(course => {
            if (course.title.toLowerCase().includes(e.target.value.toLowerCase())) {
              filteredResults.push({
                program: program.program,
                level: level.level,
                ...course,
              });
            }
          });
        });
      });
      setResults(filteredResults);
    }
  };

  return (
    <div className="rechercher-page">
      <div className="search-container">
        <h1 className="primary-heading">Rechercher</h1>
        <input
          type="text"
          placeholder="Rechercher un cours"
          value={query}
          onChange={handleSearch}
          className="search-input"
        />
        <div className="search-results">
          {results.length > 0 ? (
            results.map(result => (
              <div key={result.id} className="search-result-item">
                <h3>{result.title}</h3>
                <p>{result.description}</p>
                <p><strong>Programme:</strong> {result.program}</p>
                <p><strong>Niveau:</strong> {result.level}</p>
              </div>
            ))
          ) : (
            <p>Aucun résultat trouvé</p>
          )}
        </div>
      </div>
    </div>
  );
};

export default Rechercher;
